### ISSUE TITLE
Update preferred auth type if auth type is 'webauthn' when key is removed

### ISSUE THREAD

**Issue by winterweird** [difi/dc18-webAuth#76]
**Motivation:** It makes no sense to have auth-type "webauthn" when there is no security key anymore. If the security key is removed, the auth-type should also be reset to a different value (or null).

**Files:**
- *either* update-localstorage-fields.js
- *or* update-settings-eventbindings.js

**Solution:** Either check that the auth-type makes sense and possibly reset it when calling updateFields() function in update-localstorage-fields.js, or perform the update when selecting to remove the security key, in the event listener for btn-submit-remove in update-settings-eventbindings.js

**Comment by viktorfa** [comment]
I did it on the webauthn:remove-device event in localStorage.js
